# Fancy but Useful Tensor Operations

In [1]:
import torch
import numpy as np

## 增减维度：squeeze & unsqueeze

In [ ]:
x0 = torch.tensor([1, 2, 3])
print("Original tensor:")
print(x0, x0.shape)

# Add a new dimension at position 0
x1 = x0.unsqueeze(0)
print("\nAdd a new dimension at position 0:")
print(x1, x1.shape)

# Add a new dimension at position 1
x2 = x0.unsqueeze(1)
print("\nAdd a new dimension at position 1:")
print(x2, x2.shape)

Original tensor:
tensor([1, 2, 3]) torch.Size([3])

Add a new dimension at position 0:
tensor([[1, 2, 3]]) torch.Size([1, 3])

Add a new dimension at position 1:
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])


In [9]:
y0 = torch.rand(1, 3, 1, 5)
print("Original tensor shape:", y0.shape)

# Remove all dimensions of size 1
y1 = y0.squeeze()
print("\nShape after removing all dimensions of size 1:", y1.shape)

# Remove dimension at position 0
y2 = y0.squeeze(0)
print("\nShape after removing dim=0:", y2.shape)

Original tensor shape: torch.Size([1, 3, 1, 5])

Shape after removing all dimensions of size 1: torch.Size([3, 5])

Shape after removing dim=0: torch.Size([3, 1, 5])


## 合并张量：cat & stack

In [14]:
t1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9],
                   [10, 11, 12]])
print("Original tensors:")
print(t1, t1.shape)
print(t2, t2.shape)

# Concatenate t1 and t2 along dimension 0
t3 = torch.cat((t1, t2), dim=0)
print("\nConcatenated on dim=0:")
print(t3, t3.shape)

# Concatenate t1 and t2 along dimension 1
t4 = torch.cat((t1, t2), dim=1)
print("\nConcatenated on dim=1:")
print(t4, t4.shape)

Original tensors:
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])

Concatenated on dim=0:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]) torch.Size([4, 3])

Concatenated on dim=1:
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]) torch.Size([2, 6])


In [15]:
t1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
t2 = torch.tensor([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])
print("Original tensors:")
print(t1, t1.shape)
print(t2, t2.shape)

# Stack t1 and t2 along dimension 0
t3 = torch.stack((t1, t2), dim=0)
print("\nStacked on dim=0:")
print(t3, t3.shape)

# Stack t1 and t2 along dimension 1
t4 = torch.stack((t1, t2), dim=1)
print("\nStacked on dim=1:")
print(t4, t4.shape)

Original tensors:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]) torch.Size([3, 3])

Stacked on dim=0:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]) torch.Size([2, 3, 3])

Stacked on dim=1:
tensor([[[ 1,  2,  3],
         [10, 11, 12]],

        [[ 4,  5,  6],
         [13, 14, 15]],

        [[ 7,  8,  9],
         [16, 17, 18]]]) torch.Size([3, 2, 3])


## 扩展张量：expand & repeat

In [ ]:
x0 = torch.tensor([[1], [2], [3]]) # shape: (3, 1)
print("Original tensor:")
print(x0, x0.shape)

# Expand the dimension of size 1 to size 4.
x1 = x0.expand(3, 4)
print("\nExpanded tensor:")
print(x1, x1.shape)

# Modify an element in the original tensor
x0[0][0] = 100
print("\nExpanded tensor after modifying original tensor:")
print(x1, x1.shape)

Original tensor:
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])

Expanded tensor:
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])

Expanded tensor after modifying original tensor:
tensor([[100, 100, 100, 100],
        [  2,   2,   2,   2],
        [  3,   3,   3,   3]]) torch.Size([3, 4])


In [25]:
x0 = torch.tensor([[1], [2], [3]]) # shape: (3, 1)
print("Original tensor:")
print(x0, x0.shape)

# Repeat the tensor 3 times along dimension 1
x1 = x0.repeat(1, 3)
print("\nRepeated tensor:")
print(x1, x1.shape)

# Modify an element in the original tensor
x0[0][0] = 100
print("\nRepeated tensor after modifying original tensor:")
print(x1, x1.shape)

Original tensor:
tensor([[1],
        [2],
        [3]]) torch.Size([3, 1])

Repeated tensor:
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]) torch.Size([3, 3])

Repeated tensor after modifying original tensor:
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]) torch.Size([3, 3])


## 高级索引：gather & scatter_

In [22]:
# Assume batch_size=2, num_actions=4
# Each row represents a state, and each column represents the Q-value for an action.
q_values = torch.tensor([[0.1, 0.5, 0.2, 0.2],  # Q-values for state 1
                         [0.8, 0.1, 0.05, 0.05]]) # Q-values for state 2

# Assume these are the actions we actually took for each state
# (action 1 for the first state, action 0 for the second state).
# Note the shape is (2, 1) to match the dimensions needed for gather.
actions = torch.tensor([[1], [0]])

# dim=1 means we are indexing along the action dimension.
# index==actions tells gather which column to pick for each row.
# For row 0, it will pick the element at index 1 (which is 0.5).
# For row 1, it will pick the element at index 0 (which is 0.8).
selected_q_values = torch.gather(q_values, dim=1, index=actions)

print("Q-Values:")
print(q_values, q_values.shape)
print("Actions:")
print(actions, actions.shape)
print("\nGathered Q-Values:")
print(selected_q_values, selected_q_values.shape)

Q-Values:
tensor([[0.1000, 0.5000, 0.2000, 0.2000],
        [0.8000, 0.1000, 0.0500, 0.0500]]) torch.Size([2, 4])
Actions:
tensor([[1],
        [0]]) torch.Size([2, 1])

Gathered Q-Values:
tensor([[0.5000],
        [0.8000]]) torch.Size([2, 1])


In [ ]:
# Assume batch_size=4, num_classes=5
# Class labels
labels = torch.tensor([1, 4, 2, 0])

# 1. Create a base tensor of zeros with shape (batch_size, num_classes)
one_hot = torch.zeros(4, 5)

# 2. Prepare the index and src arguments
# The index tensor needs to have the same number of dimensions as the
# one_hot tensor, so we use unsqueeze to add a dimension.
# labels.unsqueeze(1) gives it the shape (4, 1).
labels = labels.unsqueeze(1)
value = 1.0 # The value we want to fill in

# 3. Use scatter_ to perform the one-hot encoding
# dim=1 means we will be scattering values along the columns,
# at the positions specified by 'index'.
one_hot.scatter_(dim=1, index=labels, value=value)

print("Labels:")
print(labels, labels.shape)
print("\nOne-Hot Encoding:")
print(one_hot, one_hot.shape)

Labels:
tensor([[1],
        [4],
        [2],
        [0]]) torch.Size([4, 1])

One-Hot Encoding:
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.]]) torch.Size([4, 5])
